baseURL = 'http://sickcallfuu.github.io/'
languageCode = 'en-us'
title = 'sickcallfuu'
theme = 'blank'

custom_css = "css/style.css"



[[menu.main]]
  name = 'all posts'
  url = '/posts'
  weight = 1

[[menu.main]]
  name = 'tags'
  url = '/tags'
  weight = 2

[[menu.main]]
  name = 'about'
  url = '/about'
  weight = 3
